title: Marcus Presutti
description: "List of projects by Marcus Presutti"
author:
  name: "Marcus Presutti"
  email: "marcus.presutti.eu@gmail.com"
  url: "https://ashishchaudhary.in/hacker-blog"

baseurl: "/monthly_projects"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "marcus.presutti"
year : "2025"

sass:
  sass_dir: _sass

include:
  - assets